// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnvyzesxlyyivjkauwbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudnl6ZXN4bHl5aXZqa2F1d2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzQ4MzIsImV4cCI6MjA2NzIxMDgzMn0.TJpkpfaEcp78djBCW0dHG3I_ldT6CE67W_d5432ffNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});